version: '3.9'
services:
  api:
    depends_on:
      - postgredb
    container_name: fastbank-api
    build: 
      context: .
    ports:
      - 8056:8000
    volumes:
      - ./code:/code
    env_file:
      - ./.env
    networks:
      - compose-bridge

  postgredb:
    container_name: postgredb
    image: postgres:13-alpine
    volumes: 
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - compose-bridge

networks:
  compose-bridge:
    driver: bridge