version: '3.9'
services:
  api:
    depends_on:
      - psql
    container_name: fastbank-api
    build: 
      context: .
    ports:
      - 8056:8000
    volumes:
      - fastbank-volume:/code
    env_file:
      - ./.env
    networks:
      - compose-bridge

  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes: 
      - fastbank-volume-db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - compose-bridge

networks:
  compose-bridge:
    driver: bridge

volumes:
  fastbank-volume:

  fastbank-volume-db:
