# Generated by Django 4.2.6 on 2023-10-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='CardTransaction',
        ),
        migrations.AlterModelOptions(
            name='cardtransaction',
            options={'verbose_name': 'Card transaction', 'verbose_name_plural': 'Card transactions'},
        ),
    ]
