# Generated by Django 4.2.6 on 2023-10-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_transaction_cardtransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalperson',
            name='rg',
            field=models.CharField(max_length=9),
        ),
    ]
